name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    env:
      VERSION: "0.1.0"

    steps:
    - uses: actions/checkout@v3
    - name: Stop the Docker container
      run: docker stop nextjs-docker || true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nextjs-docker:$VERSION
    - name: Run the Docker container
      run: docker run -d -p 3000:3000 --name nextjs-docker nextjs-docker:$VERSION
